<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-18T09:16:53 PDT" name="Default suite" finished-at="2020-09-18T09:17:03 PDT" duration-ms="9757">
    <groups>
    </groups>
    <test started-at="2020-09-18T09:16:53 PDT" name="Default test" finished-at="2020-09-18T09:17:03 PDT" duration-ms="9757">
      <class name="com.costcutters.testcases.FindStoreLocation">
        <test-method is-config="true" signature="launchbrowser()[pri:0, instance:com.costcutters.testcases.FindStoreLocation@5e316c74]" started-at="2020-09-18T09:16:53 PDT" name="launchbrowser" finished-at="2020-09-18T09:17:02 PDT" duration-ms="9456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrowser -->
        <test-method signature="checkthestorelocation()[pri:0, instance:com.costcutters.testcases.FindStoreLocation@5e316c74]" started-at="2020-09-18T09:17:02 PDT" name="checkthestorelocation" finished-at="2020-09-18T09:17:03 PDT" duration-ms="272" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.costcutters.testcases.FindStoreLocation.checkthestorelocation(FindStoreLocation.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkthestorelocation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.costcutters.testcases.FindStoreLocation@5e316c74]" started-at="2020-09-18T09:17:03 PDT" name="teardown" finished-at="2020-09-18T09:17:04 PDT" duration-ms="816" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.costcutters.testcases.FindStoreLocation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
